### ISSUE TITLE
Clock - Unspecified error but it works on NW ABAP

### ISSUE THREAD

**Issue by aferngas** [exercism/abap#102] opened 2022-04-01 00:42 UTC
When I run the tests for my solution it ends without specifying the error:

![image](https://user-images.githubusercontent.com/20236851/161172012-931f6b27-d968-41d9-9531-8032e38de13c.png)

The solution tests fine in a Netweaver 7.4 system.

Here is the code I'm trying:

```abap
CLASS zcl_clock DEFINITION PUBLIC CREATE PUBLIC.
  PUBLIC SECTION.
    METHODS constructor
      IMPORTING
        !hours   TYPE i
        !minutes TYPE i DEFAULT 0.
    METHODS get
      RETURNING
        VALUE(result) TYPE string.
    METHODS add
      IMPORTING
        !minutes TYPE i.
    METHODS sub
      IMPORTING
        !minutes TYPE i.

  PRIVATE SECTION.
    TYPES:
      BEGIN OF type_s_time,
        hours   TYPE i,
        minutes TYPE i,
      END OF type_s_time.

    DATA _time TYPE i.

    METHODS:
      _convert_in
        IMPORTING
          is_time        TYPE type_s_time
        RETURNING
          VALUE(rv_time) TYPE i,
      _convert_out
        IMPORTING
          iv_time        TYPE i
        RETURNING
          VALUE(rs_time) TYPE type_s_time.

ENDCLASS.

CLASS zcl_clock IMPLEMENTATION.
  METHOD add.
    _time = _convert_in( VALUE #( minutes = _time + minutes ) ).
  ENDMETHOD.

  METHOD constructor.
    _time = _convert_in( VALUE #( hours   = hours
                                  minutes = minutes ) ).
  ENDMETHOD.

  METHOD get.
    DATA(ls_time) = _convert_out( _time ).
    result = |{ ls_time-hours PAD = '0' WIDTH = 2 ALIGN = RIGHT }:{ ls_time-minutes PAD = '0' WIDTH = 2 ALIGN = RIGHT }|.
  ENDMETHOD.

  METHOD sub.
    _time = _convert_in( VALUE #( minutes = _time - minutes ) ).
  ENDMETHOD.

  METHOD _convert_in.
    DATA(ls_time) = is_time.

    IF ls_time-hours < 0.
      ls_time-hours = 24 + frac( CONV decfloat34( ls_time-hours / 24 ) ) * 24.
    ENDIF.

    IF ls_time-minutes < 0.
      ls_time-minutes = 1440 + frac( CONV decfloat34( ls_time-minutes / 1440 ) ) * 1440.
    ENDIF.

    rv_time = CONV decfloat34( frac( ( ls_time-hours * 60 + ls_time-minutes ) / 1440 ) ) * 1440.
  ENDMETHOD.

  METHOD _convert_out.
    rs_time-hours   = trunc( CONV decfloat34( iv_time / 60 ) ).
    rs_time-minutes = CONV decfloat34( frac( iv_time / 60 ) ) * 60.
  ENDMETHOD.
ENDCLASS.
```

**Comment by pokrakam** [comment] 2022-04-01 01:10
Thanks, looks like bug with multiple string template formatting directive. Have raised root cause issue at https://github.com/abaplint/transpiler/issues/683

Interesting you've done this completely without a time data type :-)

**Comment by larshp** [comment] 2022-04-01 06:24
https://github.com/abaplint/transpiler/pull/684

**Comment by aferngas** [comment] 2022-04-01 07:11
> Thanks, looks like bug with multiple string template formatting directive. Have raised root cause issue at [abaplint/transpiler#683](https://github.com/abaplint/transpiler/issues/683)
> 
> Interesting you've done this completely without a time data type :-)

Oops! It seems that I misunderstood the statement of the exercise and made it more difficult for myself. :sweat_smile:

**Comment by pokrakam** [comment] 2022-04-01 11:19
> Oops! It seems that I misunderstood the statement of the exercise and made it more difficult for myself. 😅

Many exercises are shared across tracks (one of the things that makes the site great), so they won't necessarily be ABAP-specific. Some will be easier in ABAP than in others, and vice versa. ABAP's time data is an advantage here :)

**Comment by larshp** [comment] 2022-04-08 10:10
https://github.com/abaplint/transpiler/issues/683

**Comment by mbtools** [comment] 2022-05-29 14:10
Hi @aferngas 

`decfloat34` isn't fully working on Exercism yet. Your solution works if you replace `decfloat34` with type `p` for example:

```abap
TYPES type_dec TYPE p LENGTH 15 DECIMALS 5.

...

  METHOD _convert_in.
    DATA(ls_time) = is_time.

    IF ls_time-hours < 0.
      ls_time-hours = 24 + frac( CONV type_dec( ls_time-hours / 24 ) ) * 24.
    ENDIF.

    IF ls_time-minutes < 0.
      ls_time-minutes = 1440 + frac( CONV type_dec( ls_time-minutes / 1440 ) ) * 1440.
    ENDIF.

    rv_time = CONV type_dec( frac( ( ls_time-hours * 60 + ls_time-minutes ) / 1440 ) ) * 1440.
  ENDMETHOD.

  METHOD _convert_out.
    rs_time-hours   = trunc( CONV type_dec( iv_time / 60 ) ).
    rs_time-minutes = CONV type_dec( frac( iv_time / 60 ) ) * 60.
  ENDMETHOD.
```

Best,
Marc

**Comment by larshp** [comment] 2022-07-30 09:53
current status:

![image](https://user-images.githubusercontent.com/5888506/181905156-bddbeafa-acf6-4848-aaf4-6d3ad897528f.png)

**Comment by larshp** [comment] 2022-10-31 16:30
https://github.com/abaplint/transpiler/pull/967

**Comment by larshp** [comment] 2022-10-31 17:00
@aferngas try again

![image](https://user-images.githubusercontent.com/5888506/199065509-f9f86e48-911c-4c7c-9cf6-47688fcbe39a.png)

**Comment by larshp** [comment] 2022-11-07 05:53
@aferngas did you have time to test it?

**Comment by larshp** [comment] 2022-11-15 15:58
closing, no reply

**Closed by larshp** 2022-11-15 15:58 UTC
