### ISSUE TITLE
For Group ... Group By ... not supported

### ISSUE THREAD

**Issue by GirodFred** [exercism/abap#186] opened 2022-09-16 14:06 UTC
Hi team,

I have tried SELECT it was not supported (I just see another Issue for it) and my second chance was to try the Group statement.
It works on Eclipse on 7.51 but not in Exercism

```
    aggregated_data = VALUE #(
                        FOR GROUPS grouping_group OF initial_line IN initial_numbers
                        GROUP BY ( group = initial_line-group )
                        ( group = grouping_group-group
                          count = ''
                          sum   = REDUCE #(
                                    INIT subtotal = 0
                                    FOR group_line IN GROUP grouping_group
                                    NEXT subtotal = subtotal + group_line-number )
                        ) ).
```

**Comment by bpawanchand** [comment] 2022-09-16 14:08
Hello Team,

Even I am facing the same issue.

Thanks
<img width="941" alt="Errr" src="https://user-images.githubusercontent.com/7965050/190658468-a7be4ee0-e184-4fda-979f-260675f97acf.png">

**Comment by larshp** [comment] 2022-09-16 14:12
@GirodFred can you help pasting a code snippet that passes the syntax check?

**Comment by GirodFred** [comment] 2022-09-16 14:17
> can you help pasting a code snippet that passes the syntax check?

Sorry @larshp, I don't understand, you need the code in eclipse or in Exercism ?

**Comment by larshp** [comment] 2022-09-16 14:19
just something that can be used for reproducing the issue

**Comment by bpawanchand** [comment] 2022-09-16 14:21
> just something that can be used for reproducing the issue
> 
> also, do you get a parser error, or the wrong result when the code is run on Exercism?


You can use below code to check

```
 aggregated_data = VALUE aggregated_data( BASE aggregated_data
                                            FOR GROUPS ls_group OF ls_numgrp IN initial_numbers
                                              GROUP BY ( group = ls_numgrp-group  count = GROUP SIZE )
                                                   ASCENDING
                                            ( REDUCE aggregated_data_type(
                                              INIT ls_agr_data = VALUE aggregated_data_type( )
                                               FOR ls_grp_data IN GROUP ls_group
                                              NEXT ls_agr_data = VALUE #(
                                                                      group = ls_group-group
                                                                      count = ls_group-count
                                                                      sum = REDUCE i( INIT lv_sum = 0
                                                                                       FOR lv_cal_sum IN GROUP ls_group
                                                                                      NEXT lv_sum = lv_sum + lv_cal_sum-number )
                                                                      max = REDUCE i( INIT lv_max = 0
                                                                                       FOR lv_max_num IN GROUP ls_group
                                                                                      NEXT lv_max = nmax( val1 = lv_max
                                                                                                          val2 = lv_max_num-number ) )
                                                                      min = REDUCE i( INIT lv_min = 101
                                                                                       FOR lv_min_num IN GROUP ls_group
                                                                                      NEXT lv_min = nmin( val1 = lv_min
                                                                                                          val2 = lv_min_num-number ) )
                                                                      average = ls_agr_data-sum / ls_agr_data-count
                                                                     )

                                           ) ) ).
```

**Comment by larshp** [comment] 2022-09-16 14:22
@bpawanchand the code does not pass a syntax check,

![image](https://user-images.githubusercontent.com/5888506/190661555-9bb6270e-2ec8-43e8-b5fd-427d6c99777d.png)

**Comment by GirodFred** [comment] 2022-09-16 14:23
the whole local test code is :

```


CLASS zcl_itab_aggregation DEFINITION
*  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    TYPES group TYPE c LENGTH 1.
    TYPES: BEGIN OF initial_numbers_type,
             group  TYPE group,
             number TYPE i,
           END OF initial_numbers_type,
           initial_numbers TYPE STANDARD TABLE OF initial_numbers_type WITH EMPTY KEY.

    TYPES: BEGIN OF aggregated_data_type,
             group   TYPE group,
             count   TYPE i,
             sum     TYPE i,
             min     TYPE i,
             max     TYPE i,
             average TYPE f,
           END OF aggregated_data_type,
           aggregated_data TYPE STANDARD TABLE OF aggregated_data_type WITH EMPTY KEY.

    METHODS perform_aggregation
      IMPORTING
        initial_numbers        TYPE initial_numbers
      RETURNING
        VALUE(aggregated_data) TYPE aggregated_data.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.



CLASS zcl_itab_aggregation IMPLEMENTATION.
  METHOD perform_aggregation.
    " add solution here
    "    select group, count( group ) as count, sum( number ) as sum,
    "           min( number ) as number, max( number ) as max,
    "           average( number ) as average
    "           into corresponding fields of table @aggregated_data
    "          from @initial_numbers
    "           group by group
    "           ##db_feature_mode[itabs_in_from_clause].
    aggregated_data = VALUE #(
                        FOR GROUPS grouping_group OF initial_line IN initial_numbers
                        GROUP BY ( group = initial_line-group )
                        ( group = grouping_group-group
                          count = ''
                          sum   = REDUCE #(
                                    INIT subtotal = 0
                                    FOR group_line IN GROUP grouping_group
                                    NEXT subtotal = subtotal + group_line-number )
                        ) ).


  ENDMETHOD.



ENDCLASS.
```

**Comment by bpawanchand** [comment] 2022-09-16 14:23
@larshp  this was the code snippet which  I wanted to  used in the ITAB aggregation exercise where the whole class is defined with all the needed types and data objects.

**Comment by bpawanchand** [comment] 2022-09-16 14:24
The full code is here 
```
CLASS zcl_itab_aggregation DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    TYPES group TYPE c LENGTH 1.
    TYPES: BEGIN OF initial_numbers_type,
             group  TYPE group,
             number TYPE i,
           END OF initial_numbers_type,
           initial_numbers TYPE STANDARD TABLE OF initial_numbers_type WITH EMPTY KEY.

    TYPES: BEGIN OF aggregated_data_type,
             group   TYPE group,
             count   TYPE i,
             sum     TYPE i,
             min     TYPE i,
             max     TYPE i,
             average TYPE f,
           END OF aggregated_data_type,
           aggregated_data TYPE STANDARD TABLE OF aggregated_data_type WITH EMPTY KEY.

    METHODS perform_aggregation
      IMPORTING
        initial_numbers        TYPE initial_numbers
      RETURNING
        VALUE(aggregated_data) TYPE aggregated_data.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.



CLASS zcl_itab_aggregation IMPLEMENTATION.
  METHOD perform_aggregation.
  aggregated_data = VALUE aggregated_data( BASE aggregated_data
                                            FOR GROUPS ls_group OF ls_numgrp IN initial_numbers
                                              GROUP BY ( group = ls_numgrp-group  count = GROUP SIZE )
                                                   ASCENDING
                                            ( REDUCE aggregated_data_type(
                                              INIT ls_agr_data = VALUE aggregated_data_type( )
                                               FOR ls_grp_data IN GROUP ls_group
                                              NEXT ls_agr_data = VALUE #(
                                                                      group = ls_group-group
                                                                      count = ls_group-count
                                                                      sum = REDUCE i( INIT lv_sum = 0
                                                                                       FOR lv_cal_sum IN GROUP ls_group
                                                                                      NEXT lv_sum = lv_sum + lv_cal_sum-number )
                                                                      max = REDUCE i( INIT lv_max = 0
                                                                                       FOR lv_max_num IN GROUP ls_group
                                                                                      NEXT lv_max = nmax( val1 = lv_max
                                                                                                          val2 = lv_max_num-number ) )
                                                                      min = REDUCE i( INIT lv_min = 101
                                                                                       FOR lv_min_num IN GROUP ls_group
                                                                                      NEXT lv_min = nmin( val1 = lv_min
                                                                                                          val2 = lv_min_num-number ) )
                                                                      average = ls_agr_data-sum / ls_agr_data-count
                                                                     )

                                           ) ) ).
   
  ENDMETHOD.

ENDCLASS.
```

**Comment by bpawanchand** [comment] 2022-09-16 14:27
@larshp You can check the below code  by creating a executable program

```
CLASS zcl_itab_aggregation DEFINITION.

  PUBLIC SECTION.
    TYPES group TYPE c LENGTH 1.
    TYPES: BEGIN OF initial_numbers_type,
             group  TYPE group,
             number TYPE i,
           END OF initial_numbers_type,
           initial_numbers TYPE STANDARD TABLE OF initial_numbers_type WITH EMPTY KEY.

    TYPES: BEGIN OF aggregated_data_type,
             group   TYPE group,
             count   TYPE i,
             sum     TYPE i,
             min     TYPE i,
             max     TYPE i,
             average TYPE f,
           END OF aggregated_data_type,
           aggregated_data TYPE STANDARD TABLE OF aggregated_data_type WITH EMPTY KEY.

    METHODS perform_aggregation
      IMPORTING
        initial_numbers        TYPE initial_numbers
      RETURNING
        VALUE(aggregated_data) TYPE aggregated_data.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.



CLASS zcl_itab_aggregation IMPLEMENTATION.
  METHOD perform_aggregation.
    aggregated_data =  VALUE aggregated_data( BASE aggregated_data
                                              FOR GROUPS ls_group OF ls_numgrp IN initial_numbers
                                                  GROUP BY ( group = ls_numgrp-group  count = GROUP SIZE )
                                                   ASCENDING
                                            ( REDUCE aggregated_data_type(
                                              INIT ls_agr_data = VALUE aggregated_data_type( )
                                               FOR ls_grp_data IN GROUP ls_group
                                              NEXT ls_agr_data = VALUE #(
                                                                      group = ls_group-group
                                                                      count = ls_group-count
                                                                      sum = REDUCE i( INIT lv_sum = 0
                                                                                       FOR lv_cal_sum IN GROUP ls_group
                                                                                      NEXT lv_sum = lv_sum + lv_cal_sum-number )
                                                                      max = REDUCE i( INIT lv_max = 0
                                                                                       FOR lv_max_num IN GROUP ls_group
                                                                                      NEXT lv_max = nmax( val1 = lv_max
                                                                                                          val2 = lv_max_num-number ) )
                                                                      min = REDUCE i( INIT lv_min = 101
                                                                                       FOR lv_min_num IN GROUP ls_group
                                                                                      NEXT lv_min = nmin( val1 = lv_min
                                                                                                          val2 = lv_min_num-number ) )
                                                                      average = ls_agr_data-sum / ls_agr_data-count
                                                                     )

                                           ) ) ).

  ENDMETHOD.

ENDCLASS.

START-OF-SELECTION.

  DATA(lo_agr) = NEW zcl_itab_aggregation( ).
  DATA(lt_agr) = VALUE zcl_itab_aggregation=>initial_numbers( ( group = 'A' number = 10  )
*                                                              ( group = 'B' number = 5   )
                                                              ( group = 'A' number = -10   )
*                                                              ( group = 'C' number = 22  )
*                                                              ( group = 'A' number = 13  )
*                                                              ( group = 'C' number = 500 )
                                                             ).

  DATA(lt_agr_data) = lo_agr->perform_aggregation( initial_numbers = lt_agr ).
  BREAK-POINT.
```

**Comment by larshp** [comment] 2022-09-16 14:54
wip, https://github.com/abaplint/abaplint/pull/2686

**Comment by larshp** [comment] 2022-09-18 08:51
@GirodFred it looks like your solution does not work?

![image](https://user-images.githubusercontent.com/5888506/190893912-9a6b51eb-0ccf-43e2-a50b-955063026dda.png)

![image](https://user-images.githubusercontent.com/5888506/190893920-bf8296d7-35c6-4501-bd57-fc06a69b45ad.png)

**Comment by larshp** [comment] 2022-09-18 12:33
@bpawanchand try again,

![image](https://user-images.githubusercontent.com/5888506/190902257-c9561451-bb29-4ba1-ab76-4e7c021a9765.png)

**Comment by GirodFred** [comment] 2022-09-19 05:42
> @GirodFred it looks like your solution does not work?
> 

My solution wasn't finish, as the first one (with SELECT) was not reconized by the system, I don't want to write a whole code if there is another error.
And I have another problem today (for another Exercism) ;)

**Comment by bpawanchand** [comment] 2022-09-19 05:52
> @bpawanchand try again,
> 
> ![image](https://user-images.githubusercontent.com/5888506/190902257-c9561451-bb29-4ba1-ab76-4e7c021a9765.png)

@larshp  it worked. All the test cases passed. Thanks

**Comment by larshp** [comment] 2022-09-19 05:55
closing, feel free to open a new issue if(when) you find more bugs

**Closed by larshp** 2022-09-19 05:55 UTC
